# -*- http -*-

POST http://localhost:8009/products
User-Agent: Emacs
Content-Type: application/json

{
 "name" : "MyProduct",
 "price": 200
}

########

GET http://localhost:8009/products/f48db78e-4673-414a-9c19-385269a34af2
User-Agent: Emacs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTMxOTI1ODksInN1YiI6IjY0NzM0OWRhLWQxNGUtNDFiOC04NGU0LWU1NDdmNWY5NDY0NSJ9.zH3jKrfmTXX5CqkbvpQS1c4p_oMzsbFdJM1QK9wtpno

########

PUT http://localhost:8009/products/f48db78e-4673-414a-9c19-385269a34af2
User-Agent: Emacs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTMxOTI1ODksInN1YiI6IjY0NzM0OWRhLWQxNGUtNDFiOC04NGU0LWU1NDdmNWY5NDY0NSJ9.zH3jKrfmTXX5CqkbvpQS1c4p_oMzsbFdJM1QK9wtpno

{
 "name" : "My Product Updated 2",
 "price": 2000
}

########

DELETE http://localhost:8009/products/90c0393d-0bbe-4d72-bdb3-9a27c769c9ff
User-Agent: Emacs
Content-Type: application/json

########

GET http://localhost:8009/products/90c0393d-0bbe-4d72-bdb3-9a27c769c9ff
User-Agent: Emacs
Content-Type: application/json

########

GET http://localhost:8009/products
User-Agent: Emacs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTMxOTI1ODksInN1YiI6IjY0NzM0OWRhLWQxNGUtNDFiOC04NGU0LWU1NDdmNWY5NDY0NSJ9.zH3jKrfmTXX5CqkbvpQS1c4p_oMzsbFdJM1QK9wtpno

######## testing `page` and `limit`

GET http://localhost:8009/products?page=1
User-Agent: Emacs
Content-Type: application/json


GET http://localhost:8009/products?limit=2
User-Agent: Emacs
Content-Type: application/json

GET http://localhost:8009/products?page=1&limit=2
User-Agent: Emacs
Content-Type: application/json

GET http://localhost:8009/products?page=1&limit=abc
User-Agent: Emacs
Content-Type: application/json
