version: '3.1'

volumes:
  data:

services:

  db:
    image: mariadb
    restart: always
    container_name: godockerDB
    environment:
      MARIADB_ROOT_PASSWORD: pass
      MYSQL_DATABASE: goexpert
      MYSQL_USER: buddhilw
      MYSQL_PASSWORD: pass
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
